### ISSUE TITLE
cannot run cgum when diff two C files

### ISSUE THREAD

**Issue by xiaotili0123** [GumTreeDiff/cgum#11]
When I want to use gumTree to diff two C files, I received an error like this:

java.io.IOException: Cannot run program "cgum" (in directory "/tmp"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.gumtreediff.gen.ExternalProcessTreeGenerator.readStandardOutput(ExternalProcessTreeGenerator.java:34)
	at com.github.gumtreediff.gen.c.CTreeGenerator.generate(CTreeGenerator.java:57)
	at com.github.gumtreediff.gen.TreeGenerator.generateTree(TreeGenerator.java:38)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.reader(TreeGenerator.java:77)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:65)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:69)
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:43)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.getTreeContext(AbstractDiffClient.java:133)
	at com.github.gumtreediff.client.diff.web.WebDiff.lambda$configureSpark$2(WebDiff.java:108)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more

I have installed the cgum locally and changed the gt.cgum.path parameter in gen.c main file to the path of cgum in my server. Could someone please help with this?

**Comment by xiaotili0123** [comment]
I made a mistake when adding it to the system path, now it's solved.

**Comment by BM-WuKong** [comment]
I also met this problem. Could you tell me how to add cgum to system path?

**Comment by jrfaller** [comment]
It depends on your OS.
